---
# Rook Dashboard HTTPRoute - Infra Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rook-dashboard
  namespace: rook-ceph
spec:
  parentRefs:
    - name: infra-gateway
      namespace: kube-system
  hostnames:
    - "rook.infra.k8s.wlkr.ch"
  rules:
    - backendRefs:
        - name: rook-ceph-mgr-dashboard
          port: 7000
