---
# Rook Dashboard HTTPRoute - Infra Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rook-dashboard
  namespace: rook-ceph
spec:
  parentRefs:
    - name: infra-gateway
      namespace: kube-system
  hostnames:
    - "rook.infra.k8s.wlkr.ch"
  rules:
    - filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Strict-Transport-Security
                value: "max-age=31536000; includeSubDomains"
              - name: X-Content-Type-Options
                value: "nosniff"
              - name: X-Frame-Options
                value: "SAMEORIGIN"
              - name: Referrer-Policy
                value: "strict-origin-when-cross-origin"
      backendRefs:
        - name: rook-ceph-mgr-dashboard
          port: 7000
