---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph
    targetRevision: v1.16.1
    helm:
      valuesObject:
        monitoring:
          enabled: true
        csi:
          enableRbdDriver: true
          enableCephfsDriver: false
          provisionerReplicas: 1
          csiRBDPluginResource: |
            - name: driver-registrar
              resource:
                requests:
                  memory: 32Mi
                  cpu: 25m
                limits:
                  memory: 128Mi
            - name: csi-rbdplugin
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
