apiVersion: k8up.io/v1
kind: Schedule
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"k8up.io/v1","kind":"Schedule","metadata":{"annotations":{"argocd.argoproj.io/sync-options":"SkipDryRunOnMissingResource=true"},"labels":{"argocd.argoproj.io/instance":"nextcloud"},"name":"daily-backup","namespace":"nextcloud"},"spec":{"backend":{"local":{"mountPath":"/mnt/backup"},"repoPasswordSecretRef":{"key":"password","name":"backup-repo-creds"},"volumeMounts":[{"mountPath":"/mnt/backup","name":"backup-repo"}]},"backup":{"failedJobsHistoryLimit":3,"schedule":"0 4 * * *","successfulJobsHistoryLimit":3},"check":{"schedule":"0 6 * * 1"},"prune":{"retention":{"keepDaily":7,"keepMonthly":3,"keepWeekly":4},"schedule":"0 6 * * 0"},"volumes":[{"name":"backup-repo","persistentVolumeClaim":{"claimName":"backup-repo"}}]}}
  creationTimestamp: "2025-12-22T13:34:57Z"
  finalizers:
  - k8up.io/schedule
  generation: 3
  labels:
    argocd.argoproj.io/instance: nextcloud
  name: daily-backup
  namespace: nextcloud
  resourceVersion: "1201835"
  uid: 9a1c32ff-554b-455a-9712-80106afce5cc
spec:
  backend:
    local:
      mountPath: /mnt/backup
    repoPasswordSecretRef:
      key: password
      name: backup-repo-creds
    volumeMounts:
    - mountPath: /mnt/backup
      name: backup-repo
  backup:
    failedJobsHistoryLimit: 3
    resources: {}
    schedule: 0 4 * * *
    successfulJobsHistoryLimit: 3
  check:
    resources: {}
    schedule: 0 6 * * 1
  prune:
    resources: {}
    retention:
      keepDaily: 7
      keepMonthly: 3
      keepWeekly: 4
    schedule: 0 6 * * 0
  resourceRequirementsTemplate: {}
status:
  conditions:
  - lastTransitionTime: "2025-12-22T13:34:57Z"
    message: The resource is ready
    reason: Ready
    status: "True"
    type: Ready
