---
# NFS PersistentVolume for backup exports
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-nfs
  labels:
    type: nfs
    app: backup
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-backup
  nfs:
    server: bsnas1.somuch.cloud
    path: /mnt/data/k8s/backup
---
# PVC to claim the NFS volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-storage
  namespace: backup
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-backup
  resources:
    requests:
      storage: 500Gi
