apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: backup
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  backend:
    repoPasswordSecretRef:
      name: backup-repo-creds
      key: password
    local:
      mountPath: /mnt/backup
    volumeMounts:
      - name: backup-storage
        mountPath: /mnt/backup
  backup:
    schedule: "0 3 * * *"
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3
    promURL: http://prometheus-operated.monitoring.svc:9090
    resources: {}
  check:
    schedule: "0 5 * * 1"
    resources: {}
  prune:
    schedule: "0 5 * * 0"
    resources: {}
    retention:
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 3

  resourceRequirementsTemplate: {}

  volumes:
    - name: backup-storage
      persistentVolumeClaim:
        claimName: backup-storage
