# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
---
# VolumeSnapshot CRDs from external-snapshotter
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Before other backup resources
spec:
  project: infra
  source:
    repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
    targetRevision: v8.2.0
    path: client/config/crd
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
