apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-benchmarks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JanWelker/homelab.git
    targetRevision: HEAD
    path: payload/apps/benchmarks
  destination:
    server: https://kubernetes.default.svc
    namespace: benchmarks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
