apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pelican
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JanWelker/homelab.git
    targetRevision: HEAD
    path: payload/apps/pelican
  destination:
    server: https://kubernetes.default.svc
    namespace: pelican
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
