---
# Fixed name keeps Loki's storage config static, see docs/platform/logging.md
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-bucket
  namespace: logging
spec:
  bucketName: loki
  storageClassName: ceph-bucket
