---
# Kasten K10 Dashboard HTTPRoute - Infra Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: k10-dashboard
  namespace: kasten-io
spec:
  parentRefs:
    - name: infra-gateway
      namespace: kube-system
  hostnames:
    - "backup.infra.k8s.wlkr.ch"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /k10
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /kasten-k10
      backendRefs:
        - name: gateway
          port: 80
```
