# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/core/v1/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: kasten-io
  labels:
    name: kasten-io
