# NFS-based Location Profile for K10
# This will be created via K10 API after deployment, documented here for reference
#
# K10 Location Profiles are typically created via the dashboard or K10 API
# For GitOps, we can create a Profile custom resource once K10 is running
#
# Example Profile configuration (to be applied after K10 deployment):
# apiVersion: config.kio.kasten.io/v1alpha1
# kind: Profile
# metadata:
#   name: nfs-backup-location
#   namespace: kasten-io
# spec:
#   type: Location
#   locationSpec:
#     type: NFSStore
#     nfsStore:
#       claimName: k10-backup-storage
#
# For now, we'll create a PVC that K10 can use for NFS storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k10-backup-storage
  namespace: kasten-io
spec:
  storageClassName: nfs-backup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti # NFS size is nominal
