---
site_name: Homelab Documentation
repo_name: JanWelker/homelab
repo_url: https://github.com/JanWelker/homelab
theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - content.code.copy
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture/index.md
      - Boot Process: architecture/boot-process.md
      - GitOps Strategy: architecture/gitops.md
      - Reference: architecture/directory-structure.md
  - Development:
      - Documentation System: development/documentation.md
      - Maintenance: development/maintenance.md
      - Adding a Workload: development/add-workload.md
  - Platform:
      - Overview: platform/index.md
      - Cilium: platform/cilium.md
      - Cert-Manager: platform/cert-manager.md
      - Gateway API: platform/gateway-api.md
      - Rook-Ceph: platform/rook-ceph.md
      - Infisical: platform/infisical.md
      - Monitoring: platform/monitoring.md
      - K8up: platform/k8up.md
      - Postgres Operator: platform/postgres-operator.md
  - Workloads:
      - Overview: workloads/index.md
      - Home Assistant: workloads/home-assistant.md
      - Nextcloud: workloads/nextcloud.md
      - GitHub Actions Runner: workloads/github-actions-runner.md
      - Advent Wollbi: workloads/advent-wollbi.md
      - Wichteln: workloads/wichteln.md
      - Nginx Test: workloads/nginx-test.md
  - Boot Server: boot_server/index.md
  - Ansible: ansible/index.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
