---
# Cilium 1.18+ LoadBalancer IP Pool
# Single IP configuration for shared ingress VIP
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default-pool"
spec:
  blocks:
    - cidr: "10.9.2.249/32" # Single IP for all ingress traffic
  serviceSelector:
    matchLabels:
      cilium.io/ingress: "true"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: "default-announcement"
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  interfaces:
    - ^e.*
  externalIPs: true
  loadBalancerIPs: true
