---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advent-wollbi
  namespace: advent-wollbi
  labels:
    app: advent-wollbi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advent-wollbi
  template:
    metadata:
      labels:
        app: advent-wollbi
    spec:
      containers:
        - name: nginx
          image: nginx:alpine@sha256:d436955245d0951d806af5e0ce0df7d111c9d4c6329f00f7ad69282a3be74f27
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          persistentVolumeClaim:
            claimName: advent-wollbi-www
