---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advent-wollbi
  namespace: advent-wollbi
  labels:
    app: advent-wollbi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advent-wollbi
  template:
    metadata:
      labels:
        app: advent-wollbi
    spec:
      containers:
        - name: nginx
          image: nginx:alpine@sha256:e7257f1ef28ba17cf7c248cb8ccf6f0c6e0228ab9c315c152f9c203cd34cf6d1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          persistentVolumeClaim:
            claimName: advent-wollbi-www
