apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: advent-wollbi-web
  namespace: advent-wollbi
spec:
  endpointSelector:
    matchLabels:
      app: advent-wollbi
  ingress:
    # Allow traffic from the Gateway (residing in kube-system)
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
        - matchLabels:
            "k8s:gateway.networking.k8s.io/gateway-name": apps-gateway
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
  egress:
    # Allow DNS resolution
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: advent-wollbi-updater
  namespace: advent-wollbi
spec:
  endpointSelector:
    matchLabels:
      app: advent-wollbi-updater
  egress:
    # Allow DNS resolution
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    # Allow external access for apt, pip, git
    - toCIDR:
        - "0.0.0.0/0"
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
