apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: jan@wlkr.ch
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      # DNS-01 solver for all domains via Route53
      - dns01:
          route53:
            region: eu-central-1 # Change if different
            # Uses IRSA or ambient credentials if available
            # Or explicit credentials from secret:
            accessKeyIDSecretRef:
              name: route53-credentials
              key: access-key-id
            secretAccessKeySecretRef:
              name: route53-credentials
              key: secret-access-key
