apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: jan@wlkr.ch
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      # Infra Gateway solver for *.infra.k8s.wlkr.ch
      - selector:
          dnsZones:
            - "infra.k8s.wlkr.ch"
        http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: infra-gateway
                namespace: kube-system
                kind: Gateway
      # Apps Gateway solver for *.k8s.wlkr.ch (default)
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: apps-gateway
                namespace: kube-system
                kind: Gateway
