---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-listener-extra-rbac
  namespace: arc-systems
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles"]
    verbs: ["create", "delete", "get", "patch", "update"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["create", "delete", "get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-listener-extra-rbac
  namespace: arc-systems
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-listener-extra-rbac
subjects:
  - kind: ServiceAccount
    name: arc-systems-gha-rs-controller
    namespace: arc-systems
---
# RBAC for Manual Runner (Kubernetes Mode)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-runner-admin
  namespace: arc-systems
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-runner-admin
  namespace: arc-systems
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner-admin
  namespace: arc-systems
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-runner-admin
subjects:
  - kind: ServiceAccount
    name: arc-runner-admin
    namespace: arc-systems
