---
# Apps Gateway wildcard certificate (covers all *.k8s.wlkr.ch)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-gateway-tls
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: apps-gateway-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.k8s.wlkr.ch"
    - "k8s.wlkr.ch"
---
# Infra Gateway wildcard certificate (covers all *.infra.k8s.wlkr.ch)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infra-gateway-tls
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: infra-gateway-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.infra.k8s.wlkr.ch"
    - "infra.k8s.wlkr.ch"
