---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: velero-bucket
  namespace: backup
spec:
  bucketName: velero
  storageClassName: ceph-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: etcd-backup-bucket
  namespace: backup
spec:
  bucketName: etcd-backup
  storageClassName: ceph-bucket
