---
# Home Assistant HTTPRoute - Apps Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  parentRefs:
    - name: apps-gateway
      namespace: kube-system
  hostnames:
    - "home.k8s.wlkr.ch"
  rules:
    - backendRefs:
        - name: home-assistant
          port: 8080
