---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: wichteln
  namespace: wichteln
spec:
  endpointSelector:
    matchLabels:
      app: wichteln
  ingress:
    # Allow traffic from the Gateway
    - fromEntities:
        - "ingress"
      toPorts:
        - ports:
            - port: "5000"
              protocol: TCP
          rules:
            http:
              - method: "GET"
                path: "/.*"
              - method: "POST"
                path: "/.*"
  egress:
    # Allow DNS resolution
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    # Allow connection to Postgres (wichteln-db)
    - toEndpoints:
        - matchLabels:
            application: spilo
            cluster-name: wichteln-db
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
