---
# nginx-test HTTPRoute - Apps Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-test
spec:
  parentRefs:
    - name: apps-gateway
      namespace: kube-system
  hostnames:
    - "nginx.k8s.wlkr.ch"
  rules:
    - filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Strict-Transport-Security
                value: "max-age=31536000; includeSubDomains"
              - name: X-Content-Type-Options
                value: "nosniff"
              - name: X-Frame-Options
                value: "SAMEORIGIN"
              - name: Referrer-Policy
                value: "strict-origin-when-cross-origin"
      backendRefs:
        - name: nginx-test
          port: 80
