---
# nginx-test HTTPRoute - Apps Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-test
  namespace: nginx-test
spec:
  parentRefs:
    - name: apps-gateway
      namespace: kube-system
  hostnames:
    - "nginx.k8s.wlkr.ch"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginx-test
          port: 80
