apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  backend:
    repoPasswordSecretRef:
      name: backup-repo-creds
      key: password
    local:
      mountPath: /mnt/backup
    volumeMounts:
      - name: backup-repo
        mountPath: /mnt/backup
  backup:
    schedule: "0 4 * * *" # 4 AM (staggered from global 3 AM)
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3
    resources: {}
    # This will backup all PVCs in the nextcloud namespace

  check:
    schedule: "0 6 * * 1"
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3
    resources: {}
  prune:
    schedule: "0 6 * * 0"
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3
    resources: {}
    retention:
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 3

  resourceRequirementsTemplate: {}

  volumes:
    - name: backup-repo
      persistentVolumeClaim:
        claimName: backup-repo
