---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8up-nfs-backup
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # TODO: Update with your NFS server IP and export path
    server: 10.9.0.10
    path: /mnt/data/k8s/backup
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=2
