---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: infisical
  namespace: infisical
spec:
  parentRefs:
    - name: apps-gateway
      namespace: kube-system
  hostnames:
    - "secrets.infra.k8s.wlkr.ch"
  rules:
    - backendRefs:
        - name: infisical-infisical-standalone-infisical
          port: 8080
