---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    chart: secrets-operator
    targetRevision: 0.1.0 # Using a reasonable starting version or 'latest' if acceptable, but exact version is better. I'll check latest if possible, otherwise omit to default to latest stable provided by helm repo, or use a known recent version. I'll omit version to let it float to latest for now as I didn't check exact latest version number, or I can search for it.
    # Actually, better to explicitly search for the latest version to be safe, but for now I will omit targetRevision to pick the latest, or use a placeholder if I need to be strict.
    # Let's search for the latest version first to be precise.
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
