# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JanWelker/homelab.git
    targetRevision: HEAD
    path: payload/apps
    directory:
      recurse: true
      include: "{**/application.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JanWelker/homelab.git
    targetRevision: HEAD
    path: payload/core
    directory:
      recurse: true
      exclude: "{cilium/values.yaml,README.md,**/*.template}"
  destination:
    server: https://kubernetes.default.svc
    namespace: default # individual apps should override this
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# ArgoCD manages itself via Helm after initial bootstrap
# bootstrap-argocd applies argocd-application.yaml which manages the Helm release
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JanWelker/homelab.git
    targetRevision: HEAD
    path: payload/bootstrap
    directory:
      recurse: false
      exclude: "{argocd-values.yaml}" # Values file referenced by argocd Application
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
