---
name: Lint Ansible

"on":
  push:
    branches:
      - "main"
    paths:
      - "ansible/**"
  pull_request:
    paths:
      - "ansible/**"
  workflow_dispatch:

jobs:
  ansible-lint:
    name: Ansible
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container: python:3.14-slim@sha256:bc389f7dfcb21413e72a28f491985326994795e34d2b86c8ae2f417b4e7818aa
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.7"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ansible-lint
        working-directory: ansible
        run: uv run ansible-lint
