---
name: Lint Markdown
permissions:
  contents: read

"on":
  push:
    branches:
      - "main"
    paths:
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.md"
  workflow_dispatch:

jobs:
  markdown-lint:
    name: Markdown
    runs-on: ubuntu-latest
    container: node:24.15.0-alpine@sha256:d1b3b4da11eefd5941e7f0b9cf17783fc99d9c6fc34884a665f40a06dbdfc94f
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Run markdownlint
        run: markdownlint-cli2 '**/*.md' '!**/.venv' '!.agent'
