---
name: Lint YAML
permissions:
  contents: read

"on":
  push:
    branches:
      - "main"
    paths:
      - "**/*.yaml"
  pull_request:
    paths:
      - "**/*.yaml"
  workflow_dispatch:

jobs:
  yaml-lint:
    name: YAML
    runs-on: ubuntu-latest
    container: python:3.14-slim@sha256:8a14a31f4bf634c04722154f30eb33998b4068de8b83b6b2800ec1b7238555d0
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.5"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run yamllint
        run: uv run yamllint -f github **/*.yaml
