---
name: Lint Markdown
permissions:
  contents: read

"on":
  push:
    branches:
      - "main"
    paths:
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.md"
  workflow_dispatch:

jobs:
  markdown-lint:
    name: Markdown
    runs-on: ubuntu-latest
    container: node:24.14.1-alpine@sha256:8510330d3eb72c804231a834b1a8ebb55cb3796c3e4431297a24d246b8add4d5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Run markdownlint
        run: markdownlint-cli2 '**/*.md' '!**/.venv' '!.agent'
