---
name: Lint Ansible

"on":
  push:
    branches:
      - "main"
    paths:
      - "ansible/**"
  pull_request:
    paths:
      - "ansible/**"
  workflow_dispatch:

jobs:
  ansible-lint:
    name: Ansible
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container: python:3.14-slim@sha256:f85c5697265c178cc6887276c55fe16cf3d14ca35c3df6a5eab3b360534a55d2
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          version: "0.12.23"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ansible-lint
        working-directory: ansible
        run: uv run ansible-lint
