---
name: Lint Ansible

"on":
  push:
    branches:
      - "main"
    paths:
      - "ansible/**"
  pull_request:
    paths:
      - "ansible/**"
  workflow_dispatch:

jobs:
  ansible-lint:
    name: Ansible
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container: python:3.14-slim@sha256:63a4c7f612a00f92042cbdcc7cdc6a306f38485af0a200b9c89de7d9b1607d15
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: "0.11.24"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ansible-lint
        working-directory: ansible
        run: uv run ansible-lint
