---
name: Lint YAML
permissions:
  contents: read

"on":
  push:
    branches:
      - "main"
    paths:
      - "**/*.yaml"
  pull_request:
    paths:
      - "**/*.yaml"
  workflow_dispatch:

jobs:
  yaml-lint:
    name: YAML
    runs-on: ubuntu-latest
    container: python:3.14-slim@sha256:71b358f8bff55413f4a6b95af80acb07ab97b5636cd3b869f35c3680d31d1650
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          version: "0.11.6"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run yamllint
        run: uv run yamllint -f github **/*.yaml
