---
name: Lint Markdown
permissions:
  contents: read

"on":
  push:
    branches:
      - "main"
    paths:
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.md"
  workflow_dispatch:

jobs:
  markdown-lint:
    name: Markdown
    runs-on: ubuntu-latest
    container: node:24.14.1-alpine@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Run markdownlint
        run: markdownlint-cli2 '**/*.md' '!**/.venv' '!.agent'
