---
name: Reusable Docker Build & SLSA

"on":
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: false
        type: string
        description: "Primary tag for the image (e.g. short sha)"
      context:
        required: false
        type: string
        default: .
      use_uv:
        required: false
        type: boolean
        default: false
      build_command:
        required: false
        type: string
    outputs:
      image_digest:
        description: "Image digest"
        value: ${{ jobs.build.outputs.digest }}
      image_tags:
        description: "Full image tags"
        value: ${{ jobs.build.outputs.tags }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    outputs:
      digest: ${{ steps.build-and-push.outputs.digest }}
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        if: ${{ inputs.use_uv }}
        uses: astral-sh/setup-uv@v5

      - name: Pre-build project
        if: ${{ inputs.build_command != '' }}
        run: ${{ inputs.build_command }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ inputs.image_name }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ inputs.image_tag }},enable=${{ inputs.image_tag != '' }}
            type=sha,format=short

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ inputs.image_name }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
