---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-docs
  namespace: documentation
  labels:
    app.kubernetes.io/name: homelab-docs
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: homelab-docs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homelab-docs
    spec:
      containers:
        - name: homelab-docs
          image: ghcr.io/janwelker/homelab-docs:sha-0da2f35@sha256:5b677f7ebe399a406fe51824bf86e3b1cc1d31befc7abeec5d0a84efcb6eb40f
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
