---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-docs
  namespace: documentation
  labels:
    app.kubernetes.io/name: homelab-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homelab-docs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homelab-docs
    spec:
      containers:
        - name: homelab-docs
          image: ghcr.io/janwelker/homelab-docs:sha-ac2082a@sha256:1bd3aa0da052a6a8382f08c567d6e5a913c7f5b547502a8cfe3f470ba02c0414
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
