apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: homelab-docs
  namespace: documentation
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: homelab-docs
  ingress:
    # Allow traffic from the Gateway
    - fromEntities:
        - "ingress"
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    # Allow DNS resolution
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
